---
title: "Summary and data overview"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
runtime: shiny
resource_files:
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.cpg
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.dbf
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.prj
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.sbn
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.sbx
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.shp.xml
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.shx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(sf)
library(ggrepel)
library(scales)
library(shiny)
library(shinycssloaders)
library(ggiraph)
library(kableExtra)
library(rmapshaper)
library(cowplot)
library(DT)
```

<br>

# Main themes

The variable that seemed to have the most significant impact on how an agency responded to questions in this survey was the population size served. 

*What is the estimated total population that you serve?*

* Less than 2,500 (46 responses, 24.7%)
* 2,500 - 4,999 (57 responses, 30.7%)
* 5,000 - 9,999 (28 responses, 15.1%)
* 10,000 - 14,999 (22 responses, 11.8%)
* Greater than 15,000 (27 responses, 14.5%)

The main themes based on population were;

*Characteristic section*

* Compared to agencies serving larger populations, the smaller the population served (1 - 5,000 people) the....
  + significantly less likely the agency was owned, managed or receives support from a corporate health system,
  + significantly more likely to offer basic life support,
  + significantly less likely to pay staff and rely on on-call compensation or volunteers, and
  + significantly more likely to use EMRs to staff their ambulances.
  
* Compared to agencies serving small populations, the large the population served (10,000 or more) the.....
  + significantly more likely the agency was owned, managed or receives support from a corporate health system,
  + significantly more likely to provide advanced life support,
  + significantly more likely to pay staff, and
  + significantly less likely to use EMRs to staff their ambulances.
  
In addition to this bifurcation in the relationship (larger vs smaller) there was one way in which agencies serving more "moderate" sized populations (2,500 - 10,000) differed. These agencies were significantly more likely to offer part-time advanced life support than other agencies.

*Workforce section*

* Compared to agencies serving larger populations, the smaller the population served (1 - 5,000 people) the...
  + significantly less likely the agency could cover the call schedule without undue burden or excessive time commitments,
  + significantly more likely the agency found recruiting new staff to be difficult,
  + 

<br>


The following narrative combines the executive summary written by the MN Department of Health with a summary of the results found in this analysis.

# Characteristics section

**Key Findings (MDH)**

Most rural EMS agencies provide basic life support services to relatively small populations spread across large geographic areas. Along with low daily call volumes, these realities exacerbate the inability to create sustainable business and staffing models.

* The median call volume is nearly one call per day
* Over half of the agencies cover more than 200 square miles; 37 percent cover more than 300
square miles
* Over half of the agencies serve populations of less than 5,000

However, when we dig a bit deeper we tend to see that agencies that are more rural (serve smaller population sizes) or are not owned, managed or receive support from a corporate health system follow the above narrative more so than agencies that are not as rural (serve large population sizes).

**1. Owned, managed, or receive support from a corporate health system**

Although only 27% of agencies responded that they were owned, managed or receive support from a corporate health care system, agencies that serve large population sizes were significantly more likely to respond this way - 42% of responses serving 10,000 - 14,999 and 77% of responses serving 15,000 or more people. The percent of agencies responding this way from the other population groups ranged from 17% to 13%. 

The questions raised from this relationship;

* Why are EMS agencies that serve larger populations more involved with corporate health care and vice versa?
  + More financially sustainable?
  + Large corporate healthcare systems are more likely to be located in a larger population center?

**2. Types of services provided**

*Basic life support: * Although a very large majority of all agencies (88.2%) offer basic life support, agencies that serve a small population size were significantly more likely to provide this service - 96% of responses serving less than 2,500 and 98% of responses serving 2,500 - 4,999. A large majority of agencies serving other population sizes also provide basic life support, just not at the same rate. 

*Advanced life support: * Although only 27% of all agencies offer advanced life support, agencies that serve a large population size were significantly more likely to offer this service - 63% of responses serving 10,000 - 14,999 and 92% of responses serving 15,000 or more people. The percent of agencies that responded this way were significantly lower for other population sizes - 20% of responses serving 5,000 - 9,999, 4% of responses serving 2,500 - 4,999 and 4% of responses serving less than 2,500 people.

In addition to population sizes, offering advanced life support was also related to whether an agency was owned, managed or received support from a corporate health care system - 58% of these agencies responded that they offer ALS compared to only 16% of agencies that are not owned, managed or receive support from a corporate health system.

*Part-time advanced life support: * Lastly, only 17% of all agencies responded that they offer part-time advanced life support. However, agencies serving moderate size populations were significantly more likely to offer this service - 47% of responses serving 5,000 - 9,999.

The questions raised from this relationship are;

* Why are agencies that serve a larger population more likely to offer advanced life support?
  + Are these services very expensive to offer?
  + Are there just too few instances where this type of service is necessary when the population served is small?
  + Does offering advanced life support significantly improve the odds of someone surviving a health crisis in transport? If so, does this mean that our most rural areas are essentially not receiving the same level of care due to a business model?

* What are agencies that are owned, managed or receive support from a corporate health system more likely to provide advanced life support?
  + Because these agencies are more likely to serve larger population sizes and has the revenue to provide this service?
  + Do these systems already have the equipment available?
  + Is offering advanced life support a significant capital investment and can only be attained by systems with access to resources?
  + Do healthcare systems see offering this service as a competitive advantage in the marketplace?
  
**3. Staff compensation**

A majority of agencies (57%) responded that they use a volunteer/on-call compensation structure for their staff. However, agencies that serve smaller sized populations were significantly more likely to use this framework for their staff compensation - 76% of responses serving less than 2,500 people and 77% of responses serving 2,500 - 4,999. On the flip side, only 20% of agencies responded that they paid their staff but it was much higher for agencies serving larger populations - 38% of responses serving 10,000 - 14,9999 and 84% of responses serving 15,000 people or more. 

In addition, agencies that were owned, managed or receive support from a corporate health care system were significantly more likely to pay their EMS staff - 48% of responses from these agencies compared to 10% of responses from agencies that are not owned, managed or receive support from a corporate health system.

The questions raised from these relationships are;

* Why are agencies that serve large populations more likely to pay their staff?
  + Obviously there are going to be a lot more calls for their service so it is demand to have full-time employees to respond to the calls.
  + The larger volume of calls means more revenue to pay their staff - business model.

* Why are agencies that are owned, managed or receive support from a health care system more likely to pay their staff?
  + Because most of these agencies serve larger populations which likely have a better business model for hiring and paying staff.
  + They have the flexibility to move staff from their hospital services to EMS services on the fly?

**4. Using EMRs to staff ambulances**

Although a majority of agencies responded that they do NOT use EMRs to staff their ambulances, agencies that serve small populations DO staff their ambulances using EMRs - 65% of responses serving less than 2,500 people and 51% of responses serving 2,500 - 4,999 people.

In addition, agencies that are NOT owned, managed or receive support from a corporate health system more likely DO staff their ambulances using EMRs - 50% of these agencies compared to 17% of agencies that are owned, managed, or receive support from a corporate health system.

The questions these relationships raise are;

* Why are agencies that serve smaller populations more likely to use EMRs to staff their ambulances?
  + Lack of volunteers/workforce?
  + Since these agencies are more likely to not offer advanced life support it would make sense to utilize these staff to also staff ambulances? 
  + Training requirements are too challenging and act as a barrier?
  
* Why are agencies that are NOT owned, managed or receive support from a corporate health care system more likely to use EMRs to staff ambulances?
  + Because these agencies are more likely to serve smaller populations?
  + These agencies are more likely to not pay their staff and are likely not as specialized?

<br>

# Workforce section

**Key Findings (MDH)**

Staffing shortages are a major challenge for rural EMS agencies. Eighty (80) percent utilize some version of volunteers to staff their operations. Roster sizes are decreasing, many staff are trained for multiple public functions and many call schedules are not covered 24 hours prior to the shifts.

* The active staff roster decreased for half of the agencies from the previous year
* Weekday daytime hours are the most difficult shifts to cover. However, all weekend and holiday
shifts are also difficult to cover
* About 60 percent of agencies have inadequate staff to cover their call schedule without undue
burden to the agency.
* Fifty-nine (59) percent of agencies do not have their shifts 100 percent covered at least 24 hours in
advance

Recruitment and retention of ambulance personnel continues to be a significant challenge even though:
* Emergency Medical Responders (EMRs) are now widely used to actively staff rural EMS agencies
* Most agencies cover the full cost of the continuing education courses for their staff
* Most eligible recipients take advantage of state EMS training reimbursement

However, it is worth noting that there were some differences in responses depending on the size of the population served by an agency and whether an agency is owned, managed or receives support from a corporate health system.

**1. Covering the call schedule**

Although a majority of agencies (60%) don't have enough people to cover the call schedule without undue burden or excessive time commitments, agencies that serve moderately sized populations (2,500 - 10,000) were significantly more likely to respond this way compared to the other agencies - 74% of responses serving 2,500 - 4,999 and 73% of responses serving 5,000 - 9,999. Agencies serving large populations were significantly more likely to have enough people - 67% serving 10,000 - 14,999 and 62% serving 15,000 or greater.

In addition, agencies that are owned, managed or receive support from a corporate health system were significantly more likely to respond that they had enough people to cover the call schedule - 56% of responses from these agencies vs. 33% of responses from agencies that are NOT owned, managed or receive support from a corporate health system.

Questions that these relationships raise are;

* Why are agencies that serve moderate size populations more likely to not have enough people to cover the call schedule?
  + Perhaps there is a sweet spot here. Agencies that serve populations these size aren't busy enough to generate the revenue to hire and pay staff so rely on volunteers, yet are busier (more call volume) than an agency serving very small population sizes that it's a heavier burden on the volunteers?
  + Agencies that serve larger populations are more likely to pay their staff and have full-time employees and do not have the tension of covering the call schedule with people volunteering their time like agencies serving moderate to small population sizes.
  
* Why are agencies that are owned, managed, or receive support from a corporate health system more likely to have enough people to cover the call schedule?
  + These agencies are more likely to serve larger population sizes thus are able to pay staff and have full-time employees rather than reliant on people to volunteer their time?

**2. Difficult to recruit new staff** 

Although a majority of agencies (63%) said that staff recruitment was difficult, agencies that serve low population sizes (less than 5,000) were significantly more likely to say that recruitment was difficult - 70% serving less than 2,500 and 77% of responses serving 2,500 - 4,999.

In addition, agencies that are NOT owned, managed or receive support from a corporate health system are significantly more likely to respond that recruiting new staff was difficult - 68% of responses from these agencies vs. 48% of responses from agencies that are owned, managed or receive support from a corporate health system.

On top of these is the relationship with compensation structure. 99% of agencies that compensate their staff other than pay said that staff recruitment was difficult compared to 84% of agencies that paid their staff.

The questions these relationships raise are;

* Why are agencies that serve lower population sizes more likely to find that recruiting staff is difficult?
  + Is it related to whether they pay staff or not? 
  + Career vs. volunteering?
  + Smaller pool to draw from?
  + Workforce shortages are worse in rural areas making finding volunteers doubling challenging?
  
* Why are agencies that are NOT owned, managed or receive support from a corporate health care system more likely to find staff recruitment challenging?
  + Because they are more likely to serve smaller populations thus they have all of those same challenges?
  + They don't have the flexibility to draw staff from the hospital?
    
* Why are agencies that compensate their staff other than pay say that staff recruitment is difficult?
  + More likely to serve smaller population sizes thus they have all of those same challenges?
  + More likely to be owned, managed or receive support from a corporate health system thus they have all of the same challenges?
  + Because they don't pay?
  

**3. Cross-training of EMS staff** 

Although a large majority of agencies (74%) said that their EMS staff were cross-trained in other publicly safety positions, agencies that serve the smallest population size were significantly more likely to respond this way - 91% of responses serving less than 2,500. The percentage decreases as the population size increases - all the way down to 40% of responses for agencies serving 15,000 or more people. 

The questions this relationship raises are;

* Why are the staff of agencies that serve smaller populations more likely to be cross-trained in other public safety agencies?
  + Lack of people means folks typically wear multiple hats. And to stretch resources, it may make sense that public safety staff and volunteers be trained in multiple roles.
  

**4. Obstacles to recruiting**

*Lack of availability: * 
Although a majority of agencies (62%) responded that lack of availability was an obstacle to staff recruitment, agencies that serve moderate size populations (2,500 - 10,000) were significantly more likely to respond this way - 74% of responses serving 2,500 - 4,999 and 87% of responses serving 5,000 - 9,999.

The question this relationship raises are;

* Why are agencies that serve moderate sized populations (2,500 - 10,000) the most likely to say that lack of availability is a barrier to recruitment? 
  + Do these agencies face an issue where their call volume isn't large enough to hire staff but also large enough that it stretches volunteers thin?

*Training requirements: * 
Although a majority of agencies (58%) responded that training requirements being too time consuming was a barrier to staff recruitment, the likeliness that an agency responded this way increases significantly as the size of the population decreases - 78% of responses serving less than 2,500 and 72% of responses serving 2,500 - 4,999. The other agencies ranged from 47% of responses serving 5,000 - 9,999 to 8% of responses serving greater than 15,000.

In addition, agencies that are NOT owned, managed or receive support from a corporate health system were significantly more likely to respond that training requirements taking too much time was a barrier to staff recruitment - 67% of responses for these agencies vs. only 35% of responses from agencies that ARE owned, managed or receive support from a corporate health system.

The questions these relationships raise are;

* Why does a decreasing size of the population impact whether training requirements are too time consuming and act as a barrier to staff recruitment? 
  + It's more likely that agencies that serve smaller populations also rely on volunteers, thus making training requirements a bit of burden for folks that already have full-time jobs?
  + Do the training requirements apply? These agencies typically have lower call volumes so maybe much of the training doesn't apply to volunteers for rural EMS?
* Why does an agency that is NOT owned, managed or receive support from a corporate health system more likely to say that training requirements are too time consuming and act as a barrier to staff recruitment?
  + These agencies are also more likely to serve small population sizes therefore they also have the same challenges?
  + An agency that does have some form of relationship with a health system may be able to provide more in-house training and reduces the burden that other agencies may encounter?

*Inadequate pay: *
Although 40% of all agencies responded that inadequate pay was a a barrier to staff recruitment, agencies that serve moderate size populations responded this way at a significantly higher rate - 53% of responses serving 2,500 - 4,999 and 53% of responses serving 5,000 - 9,999. The other agencies were below 40% of responses.

The questions this relationship raises are;

* Why are agencies that serve moderate sized populations more likely to say that inadequate pay is a barrier to staff recruitment?
  + These agencies may be in a sweet spot - they have a low enough call volume that they don't generate enough revenue to hire any staff yet their call volume is high enough to burden volunteers?

*Time commitment is too great: * 
Although a majority of all agencies (67%) responded that the time commitment being too great as a barrier to staff recruitment, agencies that serve low to moderate size populations were significantly more likely to respond this way - 70% of responses serving less than 2,500, 77% of responses serving 2,500 - 4,999, and 87% of responses serving 5,000 - 9,999. The responses from other population groups were below 67%.

In addition, agencies that are NOT owned, managed or receive support from a corporate health system are significantly more likely to say that the time  commitment is a barrier to staff recruitment - 77% of these agencies responded this way vs. 44% of agencies that are owned, managed or receive support from a corporate health system.

The questions this relationship raises are;

* Why are agencies that serve moderate sized populations more likely to that the time commitment is a barrier to staff recruitment?
  + These agencies may be in a sweet spot - they have a low enough call volume that they don't generate enough revenue to hire any staff yet their call volume is high enough to burden volunteers?
* Why are agencies that are NOT owned, managed, or receive support from a corporate health system more likely to say that time commitment is a barrier to staff recruitment?
  + These agencies typically serve small to moderate sized populations therefore face the same challenges?
  + These agencies are less likely to pay their staff?
  
*Child care responsibilities: *
Although only 38% of all agencies said that child care responsibilities were a barrier to staff recruitment, agencies that serve 5,000 - 9,999 population size were significantly more likely to respond this way - 67% of responses in this population category. The remaining percentages were 40% or lower in the other population categories.

In addition, agencies that are NOT owned, managed, or receive support from a corporate health system are significantely more likely to say that child care responsibilities are a barrier to staff recruitment - 48% of these agencies vs. 21% of agencies that are owned, managed or receive support.

The questions this relationship raises are;

* Why are agencies that serve moderate sized populations more likely to that the child care obligations act as a barrier to staff recruitment?
  + These agencies may be in a sweet spot - they have a low enough call volume that they don't generate enough revenue to hire any staff yet their call volume is high enough to burden volunteers?
* Why are agencies that are NOT owned, managed, or receive support from a corporate health system more likely to say that time commitment is a barrier to staff recruitment?
  + These agencies typically serve small to moderate sized populations therefore face the same challenges?
  + These agencies are less likely to pay their staff?


**5. Agency have a retention strategy** 

Half of all agencies responded that they have a retention strategy, however agencies that serve large population sizes were significantly more likely to have a retention strategy - 71% of responses serving 10,000 - 14,999 and 81% of responses serving more than 15,000. The other population groups had 44% of responses or lower.

In addition, agencies that are owned, managed or receive support from a corporate health system are significantly more likely to respond that they had developed a retention strategy - 69% of these agencies vs. 44% of agencies that are NOT owned, managed or receive support from a corporate health system.

The questions these relationships raise are;

* Why are agencies that serve large sized populations more likely to have a retention strategy?
  + These agencies have access to resources to help pay for and develop a retention strategy?
* Why are agencies that are owned, managed, or receive support from a corporate health system more likely to have developed a retention strategy?
  + These agencies typically serve large sized populations therefore have access to the same resources?
  
**6. Obstacles to retention**

*Retirements: * 
Although a large majority of agencies responded that age/retirements was a barrier to staff retention, the likelihood that this was the case for an agency increased as the size of the population served decreased - 75% of responses serving less than 2,500, 65% of responses serving 2,500 - 4,999 and 67% of responses serving 5,000 - 9,999. Less than 50% of agencies in the remaining population groups responded this way.

In addition, agencies that are NOT owned, managed or receive support from a corporate health system were significantly more likely to say that age and retirements were a barrier to staff retention - 68% of these agencies vs. 44% of agencies that were owned, managed or receive support from a corporate health system.

The questions these relationships raise are;

* Why do agencies that serve small population sizes more likely to deal with older workforce and retirements?
  + Small populations means that there may not be enough younger people.
  + Small populations typically have an older workforce already, thus any replacements are likely to be older.
  + The need for volunteers in our most rural areas is already high, thus there is a small pool to draw from.
* Why do agencies that are NOT owned, managed or receive support from a corporate health system more likely to say that age and retirements are an issue for staff retention?
  + These agencies typically serve small population sizes therefore they deal with those issues.
  + A corporate health system may have a healthier pool of staff to draw from and shift compared to these agencies.
  + These agencies are more likely to not pay their staff, making their positions not very attractive compared to other positions and volunteer opportunities.

*Excessive time commitment: * 
Although a large majority (72%) of all agencies said that the excessive time commitment or scheduling conflicts were a barrier to staff retention, agencies that serve low to moderate size populations were significantly more likely to respond this way - 80% of responses serving less than 2,500, 83% of responses serving 2,500 - 4,999, and 83% of responses serving 5,000 - 9,999.

In addition, agencies that are NOT owned, managed or receive support from a corporate health system are more likely to say that excessive time commitment is a barrier to staff retention - 82% of these agencies vs. 50% of agencies that are owned, managed or receive support from a corporate health system.

The questions these relationships raise are;

* Why is excessive time commitment such a larger issue to staff retention for agencies serving small to moderate sized populations compared to other agencies?
  + These agencies are less likely to pay their staff, making the time commitment unreasonable for volunteers.
* Why is excessive time commitment such a larger issue to staff retention for agencies that are NOT owned, managed or receive support from a corporate health system?
  + These agencies typically serve small to moderate populations thus they deal with the same issues?

*Limited advancement opportunities: * 
Although only 23% of all agencies said that limited advancement opportunities were a barrier to staff retention, agencies that serve large population sizes were significantly more likely to respond this way - 50% of responses serving 10,000 - 14,999 and 62% of responses serving 15,000 or great. The responses from the other population categories ranged from 30% to 0%.

In addition, agencies that are owned, managed or receive support from a corporate health system are more likely to say that limited advancement opportunities is a barrier to staff retention - 44% of these agencies vs. 16% of agencies that are NOT owned, managed or receive support.

The questions these relationships raise are;

* Why do agencies that serve larger populations respond that limited advancement opportunities acts as a barrier to staff retention?
  + These agencies are more likely to pay and be career oriented for employees?
  + These agencies deal more with staff turnover due to them being poached by larger, more urgan agencies that can offer advancement.


*Employer not allowing staff to leave: * 
Although only 37% of all agencies said that employers not allowing staff to leave work for a call was a barrier to staff retention, agencies that serve moderately sized populations (2,500 - 10,000) were significantly more likely to respond this way - 49% of responses serving 2,500 - 4,999 and 60% of responses serving 5,000 - 9,999.

The questions this relationship raises are;

* Why are agencies that serve moderate sized populations more likely to say employers not allowing staff to leave acts as a barrier to staff retention?
  + These agencies may be in a sweet spot - they have a low enough call volume that they don't generate enough revenue to hire any staff yet their call volume is high enough to burden volunteers and employers?
  
<br>

# Leadership section

**Key Findings (MDH)**

The largest problems that rural EMS agency managers face today, as in the past, are recruitment of staff and filling call schedules. These two management tasks seem to form a Maslow’s Hierarchy of basic management needs (see Appendix C, Question 24). It may be that efforts to address other management issues will be fruitless and/or unwelcomed until these basic needs are addressed.

* Sixty-nine (69) percent of rural EMS managers report difficulty recruiting staff despite the fact that 57.5 percent have a recruitment plan
* Over half of rural EMS managers report difficulty staffing their schedule

High leadership turnover was defined in this survey as an EMS agency having had three or more managers in the past five years. Using this definition, there is remarkably low turnover of rural EMS managers. A high majority of EMS managers have an active role in developing their budgets, but generally are not directly involved in billing.

* Eighty-six (86) percent of services did not have high turnover of their managers
* Eighty-one (81) percent of rural EMS managers have a role in developing their annual budgets
* Eighty-one (81) percent use other resources to bill, with billing agencies as the most common at
fifty-two (52) percent

However, it is worth noting that there was one difference in responses depending on whether or not an agency was owned, managed or receives support from a corporate health system. 

**Management received training** 

Although a majority of agencies (54%) responded that their management has received formal leadership or management training, agencies that are owned, managed or receive support from a corporate health system responded this way at a significantly higher rate than other agencies (77% vs. 46%).

In addition, agencies that are owned, managed or receive support from a corporate health system were significantly more likely to say that their management has received training - 77% of these agencies vs. 46% of agencies that are NOT owned, managed or receive support from a corporate health system.

The questions these relationship raise are;

* Why do agencies that serve large populations increase the likelihood that their leadership is trained?
  + These agencies have more revenue thus can afford to send their leadership to trainings?
  + These are agencies are more likely to be affiliated with a corporate health system who can provide the training in-house?
  + These agencies aren't so tight on scheduling and can allow staff to be trained without burdening others?

**Management challenge areas**

*Recruitment: * 
Although a majority of agencies (69%) responded that recruitment was a management challenge area, agencies that serve low to moderate sized populations responded this way at a significantly higher rate - 72% of responses serving less than 2,500, 84% of responses serving 2,500 - 4,999 and 77% of responses serving 5,000 - 9,999.

The questions this relationship raises are;

* Why do agencies that serve low to moderate sized populations more likely to say that recruitment was a challenge area?
  + Because these agencies are also more likely to say that staff recruitment is a challenge, besides just being a management challenge?
  + Because these agencies are more likely to lack leadership training?
  

*Retention: *
Although only 43% of all agencies responded that retention was a management challenge area, agencies serving moderate sized populations were significantly more likely to respond this way - 51% of responses serving 2,500 - 4,999 and 60% of responses serving 5,000 - 9,999.

The questions this relationship raises are;

* Why is staff retention such a larger management challenge for agencies that serve moderate sized populations?
  + These agencies fall in that sweet spot - not being able to pay but having enough busy to burden volunteers and burning them out.

*Staffing the schedule: * 
Although just over half of all agencies (51%) responded that staffing the schedule was a management challenge area, agencies that serve moderate size populations were significantly more likely to respond this way - 61% of responses serving 2,500 - 4,999 and 70% of responses serving 5,000 - 9,999. 

The questions this relationship raises are;

* Why is staffing the schedule such a larger management challenge for agencies that serve moderate sized populations?
  + These agencies fall in that sweet spot - not being able to pay but having enough busy to burden volunteers and burning them out.

*None: * 
Although only 9% of all agencies responded that there were "none" management challenge areas, agencies that serve larger populations were significantly more likely to respond this way - 17% of responses serving 10,000 - 14,999 and 27% of responses serving greater than 15,000.

* Why are agencies that serve larger sized populations more likely to say that they didn't have any management challenges?
  + These agencies are more likely to have enough revenue that their business model just works better and eliminates any challenges with trying to find staff?
  

<br>

